import FadeInOnScroll from "@/app/components/fadeInOnScroll";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "OptiFlowz - Privacy Policy",
  description: "OptiFlowz - Privacy policy - Effective date: February 2, 2026",
};

export default function PrivacyPolicy() {
    return(
        <main className="pp-main">
            <FadeInOnScroll>
                <h1 className="mainTitlePP">
                    Privacy Policy
                    <p className="text-[1rem]">Effective date: February 2, 2026</p>
                </h1>
            </FadeInOnScroll>

            <FadeInOnScroll>
                <section>
                    <h2 className="smallTitle">Introduction</h2>
                    <p>
                        OptiFlowz (“us”, “we”, or “our”) operates the <Link href="https://optiflowz.com">https://optiflowz.com</Link> website (hereinafter referred to as the “Service”).
                        This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.
                    </p>
                    <p>
                        We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.
                    </p>
                </section>
            </FadeInOnScroll>

            <FadeInOnScroll>
                <section>
                    <h2 className="smallTitle">Definitions</h2>
                    <ul>
                        <li><strong>Service:</strong> The <Link href="https://optiflowz.com">https://optiflowz.com</Link> website.</li>
                        <li><strong>Personal Data:</strong> Data about a living individual who can be identified from those data.</li>
                        <li><strong>Usage Data:</strong> Data collected automatically generated by the use of the Service.</li>
                        <li><strong>Cookies:</strong> Small files stored on your device (computer or mobile device).</li>
                        <li><strong>Data Controller:</strong> The legal person who determines the purposes for which any personal information is processed. For this policy, we are the Data Controller.</li>
                    </ul>
                </section>
            </FadeInOnScroll>

            <FadeInOnScroll>
                <section>
                    <h2 className="smallTitle">Information Collection and Use</h2>
                    <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                    
                    <h3>Types of Data Collected</h3>
                    <p><strong>Personal Data:</strong> While using our Service, we may ask you to provide us with certain personally identifiable information such as your Email address, First and Last name, Phone number, and Address.</p>
                    <p><strong>Usage Data:</strong> We may also collect information on how the Service is accessed, including IP addresses, browser types, and diagnostic data.</p>
                </section>
            </FadeInOnScroll>

            <FadeInOnScroll>
                <section>
                    <h2 className="smallTitle">Use of Data</h2>
                    <p>OptiFlowz uses the collected data for various purposes:</p>
                    <ul>
                        <li>To provide and maintain our Service</li>
                        <li>To notify you about changes to our Service</li>
                        <li>To provide customer support</li>
                        <li>To gather analysis or valuable information so that we can improve our Service</li>
                        <li>To monitor the usage of our Service and address technical issues</li>
                    </ul>
                </section>
            </FadeInOnScroll>

            <FadeInOnScroll>
                <section>
                    <h2 className="smallTitle">Legal Basis for Processing (GDPR)</h2>
                    <p>If you are from the European Economic Area (EEA), OptiFlowz's legal basis for collecting and using personal information depends on the context in which we collect it. We may process your data because:</p>
                    <ul>
                        <li>We need to perform a contract with you</li>
                        <li>You have given us permission to do so</li>
                        <li>The processing is in our legitimate interests</li>
                        <li>To comply with the law</li>
                    </ul>
                </section>
            </FadeInOnScroll>

            <FadeInOnScroll>
                <section>
                    <h2 className="smallTitle">Your Data Protection Rights</h2>
                    <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights, including the right to access, update, or delete the information we have on you, the right of rectification, and the right to object.</p>
                </section>
            </FadeInOnScroll>

            <FadeInOnScroll>
                <section>
                    <h2 className="smallTitle">Service Providers</h2>
                    <p>We may employ third party companies to facilitate our Service, such as <strong>Google Analytics</strong> for monitoring traffic and <strong>Google Ads/Facebook</strong> for remarketing purposes.</p>
                </section>
            </FadeInOnScroll>

            <FadeInOnScroll>
                <section className="contactSection">
                    <h2 className="smallTitle">Contact Us</h2>
                    <p>If you have any questions about this Privacy Policy, please contact us:</p>
                    <p>By email: <Link href="mailto:support@optiflowz.com">support@optiflowz.com</Link></p>
                </section>
            </FadeInOnScroll>
        </main>
    )
}